title: Al-amin Hamza Nababa
logo: https://github.com/Alamein/Al-amin/blob/main/files/profilepic.png
description: Certified Data Scientist| AUE Student| Mentor ArewaDs
show_downloads: False
theme: jekyll-theme-minimal
