#title: Al-amin Hamza Nababa
#logo: /files/profilepic.png
#description: Certified Data Scientist| AUE Student| Mentor ArewaDs
#show_downloads: False
#theme: jekyll-theme-minimal


title: Al-amin Hamza Nababa
logo: /files/profilepic.png
description: >
  🎓 Automotive Engineering Student | 📊 Certified Data Scientist | 🧠 Mentor @ Arewa Data Science | 🔬 Deep Learning & NLP Fellow  
  Passionate about building solutions with Data Science, Machine Learning, and Python.

theme: jekyll-theme-minimal

show_downloads: false

# Optional: Add social media links
social_links:
  github: https://github.com/Alamein
  linkedin: https://linkedin.com/in/alamin-h-nababa
  twitter: https://twitter.com/nababa_h
  email: mailto:your.alaminhnab4@gmail.com

# Optional: Add Google Analytics or custom CSS (if needed)
google_analytics: UA-XXXXXXXXX-X
# custom_css: /assets/css/custom.css
