title: Al-amin Hamza Nababa
logo: /files/profilepic.png
description: Certified Associate Data Scientist | Deep Learning & Machine Learning Specialist | Pythonista | Automotive Engineering Student | Mentor at ArewaDs & StarAcademy | Passionate About Computing & Community Development
show_downloads: False
theme: jekyll-theme-minimal
